name: Testes agendados

on:
  schedule:
  -  cron: "0/5 * * * 1-5"


jobs:
  RunTest:
    runs-on: windows-latest

    steps:
      # clonar projeto
      - name: Clonar o projeto
        uses: actions/checkout@v5

      # instalar o java
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: "24"
          distribution: "temurin"
          cache: maven

      # instalar Google Chrome (Windows)
      - name: Install latest Google Chrome
        uses: browser-actions/setup-chrome@latest

      # instalar ChromeDriver compatível
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # executar testes
      - name: Run tests
        run: mvn test -Dtest=RunCucumberTest -Dbrowser=chrome-ci

      #Gerar os relatórios
      - name: Gerar relatório
        run: mvn cluecumber-report:reporting

      #Arquivar relatório
      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Report-tests
          path: "**/target/"

# a adição do if: always() no setp de arquivo de relatório serve para que mesmo que o teste falhe
# ele gere o relatório, para mostrar o erro.
#Visto que no projeto, temos a configuração de não ignorar os erros, ou seja, quando algum teste falhar, ele para.