name: Smoke Test - PR

on:
  push:
    branches:
      - bruno
  pull_request:
    branches:
      - main

jobs:
  RunTest:
    runs-on: windows-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v5

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: "24"
          distribution: "temurin"
          cache: maven

      - name: Install Google Chrome (Windows)
        uses: browser-actions/setup-chrome@latest

      - name: Install matching ChromeDriver
        uses: browser-actions/setup-chromedriver@latest
        with:
          chrome-version: latest

      - name: Run tests
        run: mvn test -Dtest=RunCucumberTest -Dbrowser=chrome-ci

      - name: Gerar relatório
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        uses: actions/upload-artifact@v4
        with:
          name: Report-tests
          path: "**/target/"
